### ISSUE TITLE
Update to .NET 4.6.2 , 4.7.2 or .NET 4.8.1?

### ISSUE THREAD

**Issue by markusendres** [sillsdev/wesay#105]
Currently some projects are still on .NET 4.6.1. Is there a reason for this? I know this project is not developed much further - but would a update to 4.6.2 , 4.7.2 or 4.8.1 make sense? Are there already known issues for a potential transition?

.NET 4.6.1 is already retired - see: https://learn.microsoft.com/en-us/lifecycle/products/microsoft-net-framework

Or is fieldworks also staying on .NET 4.6.1 for a certain reason?

Are any dependencies not supporting this (Nugets or other Binaries)?

Is help wanted/needed?

**Comment by megahirt** [comment]
@markusendres help is definitely welcome!  All our stuff is open-source, but unfortunately there is documentation decay and tech debt in many of our repos scattered here, there and everywhere.  We are a small team spread thinly across many apps and services.  If you have an interest in helping in some capacity, I'd love to chat via email or another channel so we can talk about priorities and where development is happening in the SIL lexical app space.  WeSay hasn't really been developed in the past 7 years, but other stuff is moving forward.  We are working on a strategy to move into the future, but we are mostly limited by our small team and resources.  Please reach out to me at chris_hirt@sil.org if you'd like to know more.  Thank you!

**Comment by megahirt** [comment]
The FieldWorks question is complicated and would be easier to explain via another channel.  Bottom line is that there are dependencies keeping it at the current Framework level, but upgrading to .Net 4.8 is not an insurmountable task (but probably a long one).

**Comment by megahirt** [comment]
@markusendres thanks again - for this particular project, we are actively working on a replacement called FW Lite.  Thus, we have no plans to upgrade WeSay to a later .Net Framework version.
