### ISSUE TITLE
WeSay 1.5.47 Wasta-Linux 16.04: ibus (Cinnamon) Keyboards not detected

### ISSUE THREAD

**Issue by rik-shaw** [sillsdev/wesay#22]
WeSay doesn't support ibus keyboards in Ubuntu / Wasta-Linux 16.04.  It only supports the gnome keyboards (which Unity and Gnome-Shell use).  If keyboards aren't initialized in Unity / Gnome-Shell, and only Cinnamon has been used, for example, a crash will appear referencing a "null" value for the keyboards (I will update this issue with the crash text after I can re-produce it)

To "work around the problem", the project needs to be opened in Unity, which initializes the keyboards.  After this, the project can be opened in Cinnamon, but auto-switching of keyboards isn't supported and in the configuration no keyboards are detected.  I assume it is possible to merge fixes from fieldworks for this issue, as keyboard detection has worked for a few years in Cinnamon (and other desktops that don't re-factor ibus support like gnome does).

**Comment by rik-shaw** [comment]
Update: I am not able to reproduce this problem on my existing machine, and WeSay in Cinnamon in Wasta-Linux 16.04 seems to detect keyboards correctly and not crash with the "null" value for keyboard options.  But I have seen the problem on multiple "new installs" so something is not right.  I will try to gather information and update when I understand the issue better.

**Comment by megahirt** [comment]
Thank you Rik.  This should really be posted to issues@wesay.org  Thanks!

**Comment by rik-shaw** [comment]
Thankd Chris: I didn't see any link in the "About" to submit a bug 
report.  Also I wasn't sure between github and JIRA where to file 
manually.

**Comment by megahirt** [comment]
At the moment we are trying to keep track of WeSay bugs in JIRA.  Sorry for
the confusion.

**Comment by rik-shaw** [comment]
No problem: I think you could "disable" issues at github and maybe have 
a link to JIRA in the project readme or something?

Rik

**Comment by megahirt** [comment]
Thanks Rik.  I will close this issue for now but please open a new issue via issues@wesay.org
